### ISSUE TITLE
jsonseq.NewEncoder perhaps?

### ISSUE THREAD

**Issue by lpar** [jmank88/jsonseq#2]
I feel like it would be nice if there was a jsonseq.NewEncoder that worked analogously to json.NewEncoder, i.e.

    func jsonseq.NewEncoder(w Writer) json.Encoder {
        return json.NewEncoder(&jsonseq.RecordWriter{w})
    }

Purely cosmetic, but it would keep the API analogous to the `json` package.

**Comment by jmank88** [comment]
I had previously considered this and decided against it. At the time I was still trying not to necessarily favor the std lib, and instead make it easy to let people compose with whatever lib they want, but decoding wasn't as simple as encoding, so now I think having both `NewEncoder` and `NewDecoder` default to std lib is fine. 

An alternative would be to generalize `NewDecoder` to accept a decode `func([]byte, interface{}) error`, but then using the std lib becomes messy again (note that `json.Unmarshal` can't be used). These sort of variants are still useful for composing with other JSON libs, but can be added later in an API compatible way.

Would you like to open a PR to add `NewEncoder`? That func looks fine, but there are also some documentation and examples that should probably be updated as well.

**Comment by jmank88** [comment]
Added with https://github.com/jmank88/jsonseq/commit/a46ee9ee8e95f7acc2fd55ca5b95287fad271ae7
